### ISSUE TITLE
Possible casting issue in ModelGrid2D.java

### ISSUE THREAD

**Issue by cstawitz** [wStockhausen/DisMELS#9]
I'm not sure if this is causing the error I see, but on line 585 of ModelGrid2D.java mkp is declared as a `MaskData` argument and then passed to `calcHorizGradient()` on line 587. That argument should be a `ModelData` object.

![image](https://user-images.githubusercontent.com/7132710/37126412-c326f986-2225-11e8-8ef3-4869789fe3d5.png)

**Comment by wStockhausen** [comment]
MaskData is a subclass of ModelData, so (of course) passing a MaskData
object is equivalent to passing a ModelData object.

I need to take a look at Sarah Hinckley's P. cod IBM--she accessed some
ROMS prey fields using the "optional" (rather than "critical") ROMS model
field approach. Don't have this project on my Mac, so will have to wait
until my Windows laptop finishes some some ADMB runs that are using up all
cpu or download it from github.

Buck

***************************************************
* Dr. William T. Stockhausen                      *
***************************************************
* Resource Ecology and Fisheries Management       *
* Alaska Fisheries Science Center                 *
* National Marine Fisheries Service               *
* National Oceanic and Atmospheric Administration *
* 7600 Sand Point Way N.E.                        *
* Seattle, Washington 98115-6349                  *
***************************************************
* email: William.Stockhausen@noaa.gov             *
* voice: 206-526-4241 fax: 206-526-6723           *
* web  : http://www.afsc.noaa.gov                 *
***************************************************
All models are wrong, some are useful.--G.E.P. Box
Beware of geeks bearing equations.    --W. Buffett
***************************************************
Disclaimer: The opinions expressed above are personal
and do not necessarily reflect official NOAA policy.

**Comment by wStockhausen** [comment]
Fixed.
